# Generated by Django 2.2.13 on 2020-07-04 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('update_at', models.DateTimeField(blank=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('twitter_id', models.CharField(max_length=22, unique=True, verbose_name='Twitterスクリーンネーム')),
            ],
        ),
    ]
