# Generated by Django 2.2.13 on 2020-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
    ]
