# Generated by Django 2.2.13 on 2020-07-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200704_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(max_length=22, unique=True, verbose_name='twitter内部ID'),
        ),
    ]
