# Generated by Django 2.2.13 on 2020-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200704_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_daily',
            field=models.BooleanField(default=False, verbose_name='デイリー通知'),
        ),
    ]
