# Generated by Django 2.2.13 on 2020-07-05 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('question', models.CharField(max_length=131, verbose_name='問題文')),
                ('answers', models.TextField(verbose_name='正解文')),
            ],
        ),
    ]
