# Generated by Django 2.2.10 on 2020-04-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=140, verbose_name='キーとなるツイート')),
                ('reply', models.CharField(max_length=140, verbose_name='応答ツイート')),
            ],
        ),
    ]
