# Generated by Django 2.2.10 on 2020-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkset',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='パターン名'),
        ),
    ]
