# Generated by Django 2.2.10 on 2020-04-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_talkset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkset',
            name='trigger_body',
            field=models.CharField(default='aaa', max_length=140, verbose_name='キーとなるツイート'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkset',
            name='trigger',
            field=models.CharField(blank=True, max_length=140, verbose_name='キーとなるツイート'),
        ),
    ]
