# Generated by Django 2.2.10 on 2020-04-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20200417_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkset',
            name='trigger',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
