# Generated by Django 2.2.10 on 2020-04-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20200417_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkset',
            name='reply',
            field=models.CharField(max_length=140, verbose_name='応答'),
        ),
    ]
