# Generated by Django 2.2.10 on 2020-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20200417_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkset',
            name='reply',
            field=models.TextField(verbose_name='応答'),
        ),
    ]
