# Generated by Django 2.2.13 on 2020-07-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20200420_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=19)),
                ('closeness', models.PositiveIntegerField()),
                ('last_mentioned', models.DateTimeField(blank=True)),
            ],
        ),
    ]
