# Generated by Django 2.2.13 on 2020-09-21 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('question', models.CharField(max_length=131, verbose_name='問題文')),
                ('answers', models.TextField(verbose_name='正解文')),
            ],
        ),
        migrations.CreateModel(
            name='TalkSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='パターン名')),
                ('trigger', models.CharField(blank=True, max_length=140, null=True)),
                ('trigger_body', models.CharField(max_length=140, verbose_name='キーとなるツイート')),
                ('reply', models.TextField(verbose_name='応答')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('twitter_id', models.CharField(max_length=22, unique=True, verbose_name='twitter内部ID')),
                ('is_daily', models.BooleanField(default=False, verbose_name='デイリー通知')),
            ],
        ),
    ]
